name: tpi_sistemas_operativos_poeta_giuliano
services: 
  app:
    container_name: planificador_procesos
    build: 
      context: . 
      target: final
      dockerfile: ./docker/Dockerfile
    restart: no
    volumes:
      - ./src:/app/src:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
